# Generated by Django 5.1.7 on 2025-03-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
