# Generated by Django 5.1.7 on 2025-03-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
