# Generated by Django 5.1.7 on 2025-03-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
