# Generated by Django 5.1.7 on 2025-03-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0005_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('send_money', 'Send Money'), ('receive_money', 'Receive Money'), ('payment_request', 'Payment Request'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
