# Generated by Django 5.1.7 on 2025-03-26 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0006_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payapp.paymentrequest'),
        ),
    ]
