# Generated by Django 5.1.7 on 2025-03-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0007_transaction_payment_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='converted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
