# Generated by Django 5.1.7 on 2025-04-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0008_paymentrequest_converted_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
